[pytest]
testpaths = tests
python_files = test_*.py
filterwarnings =
    ignore:'asyncio.AbstractEventLoopPolicy' is deprecated and slated for removal in Python 3.16:DeprecationWarning:gi.events
    ignore:'asyncio.get_event_loop_policy' is deprecated and slated for removal in Python 3.16:DeprecationWarning:gi._ossighelper
